# Generated by Django 2.2.13 on 2020-06-25 17:40

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

from django_msal.models import MicrosoftUser


def add_microsoft_tenant(apps, schema_editor):
    MicrosoftTenant = apps.get_model('django_msal', 'MicrosoftTenant')
    try:
        MicrosoftTenant.objects.get(tid=settings.DJANGO_MSAL_PRIMARY_TENANT_ID)
    except:
        MicrosoftTenant.objects.create(
            tid=settings.DJANGO_MSAL_PRIMARY_TENANT_ID,
            name=settings.DJANGO_MSAL_PRIMARY_TENANT_NAME
        )

def add_microsoft_user_to_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    MicrosoftUser = apps.get_model('django_msal', 'MicrosoftUser')
    all_users = User.objects.all()
    for user in all_users:
        try:
            user.microsoftuser
        except:
            MicrosoftUser.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('django_msal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_microsoft_tenant),
        migrations.RunPython(add_microsoft_user_to_existing_users),
    ]
