# Generated by Django 2.2.13 on 2020-06-25 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=40, unique=True, verbose_name='Tenant ID')),
                ('name', models.CharField(max_length=40, verbose_name='Tenant Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('oid', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Object ID')),
                ('preferred_username', models.CharField(blank=True, max_length=254, null=True, verbose_name='Preferred Username')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_msal.MicrosoftTenant')),
            ],
        ),
    ]
