# Generated by Django 2.2.11 on 2020-08-21 16:27

from django.core.management import call_command
from django.db import migrations


def link_ms_accounts(apps, schema_editor):
    call_command('link_ms_accounts')

class Migration(migrations.Migration):

    dependencies = [
        ('django_msal', '0002_add_microsoftuser_to_existing_users'),
    ]

    operations = [
        migrations.RunPython(link_ms_accounts)
    ]
